// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 991 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int collectivegoals_autoinc_991 = 991;
	/// <summary>PID: 991 | Type: read</summary>
	public const int collectivegoals_autoinc = 991;
	public class Write
	{
		/// <summary>PID: 990 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int collectivegoals_contextmenu_990 = 990;
		/// <summary>PID: 990 | Type: write</summary>
		public const int collectivegoals_contextmenu = 990;
	}
	public class Collectivegoals
	{
		/// <summary>PID: 1000</summary>
		public const int tablePid = 1000;
		/// <summary>IDX: 0</summary>
		public const int indexColumn = 0;
		/// <summary>PID: 1001</summary>
		public const int indexColumnPid = 1001;
		public class Pid
		{
			/// <summary>PID: 1001 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsinstance_1001 = 1001;
			/// <summary>PID: 1001 | Type: read</summary>
			public const int collectivegoalsinstance = 1001;
			/// <summary>PID: 1002 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsname_1002 = 1002;
			/// <summary>PID: 1002 | Type: read</summary>
			public const int collectivegoalsname = 1002;
			/// <summary>PID: 1003 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsdescription_1003 = 1003;
			/// <summary>PID: 1003 | Type: read</summary>
			public const int collectivegoalsdescription = 1003;
			/// <summary>PID: 1004 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsstatus_1004 = 1004;
			/// <summary>PID: 1004 | Type: read</summary>
			public const int collectivegoalsstatus = 1004;
			/// <summary>PID: 1005 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsduedate_1005 = 1005;
			/// <summary>PID: 1005 | Type: read</summary>
			public const int collectivegoalsduedate = 1005;
			public class Write
			{
			}
		}
		public class Idx
		{
			/// <summary>IDX: 0 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsinstance_1001 = 0;
			/// <summary>IDX: 0 | Type: read</summary>
			public const int collectivegoalsinstance = 0;
			/// <summary>IDX: 1 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsname_1002 = 1;
			/// <summary>IDX: 1 | Type: read</summary>
			public const int collectivegoalsname = 1;
			/// <summary>IDX: 2 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsdescription_1003 = 2;
			/// <summary>IDX: 2 | Type: read</summary>
			public const int collectivegoalsdescription = 2;
			/// <summary>IDX: 3 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsstatus_1004 = 3;
			/// <summary>IDX: 3 | Type: read</summary>
			public const int collectivegoalsstatus = 3;
			/// <summary>IDX: 4 | Type: read</summary>
			[EditorBrowsable(EditorBrowsableState.Never)]
			public const int collectivegoalsduedate_1005 = 4;
			/// <summary>IDX: 4 | Type: read</summary>
			public const int collectivegoalsduedate = 4;
		}
	}
}
public class WriteParameters
{
	/// <summary>PID: 990  | Type: write | DISCREETS: Add item... = 1, Duplicate item... = 2, Separator 1 = -1, Edit item... = 10, Separator 2 = -2, Delete selected item(s) = 20</summary>
	public System.Object Collectivegoals_contextmenu {get { return Protocol.GetParameter(990); }set { Protocol.SetParameter(990, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	/// <summary>PID: 1000</summary>
	CollectivegoalsQActionTable collectivegoals { get; set; }
	object Afterstartup_dummy { get; set; }
	object Collectivegoals_contextmenu_990 { get; set; }
	object Collectivegoals_contextmenu { get; set; }
	object Collectivegoals_autoinc_991 { get; set; }
	object Collectivegoals_autoinc { get; set; }
	object Collectivegoalsinstance_1001 { get; set; }
	object Collectivegoalsinstance { get; set; }
	object Collectivegoalsname_1002 { get; set; }
	object Collectivegoalsname { get; set; }
	object Collectivegoalsdescription_1003 { get; set; }
	object Collectivegoalsdescription { get; set; }
	object Collectivegoalsstatus_1004 { get; set; }
	object Collectivegoalsstatus { get; set; }
	object Collectivegoalsduedate_1005 { get; set; }
	object Collectivegoalsduedate { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 1000</summary>
	public CollectivegoalsQActionTable collectivegoals { get; set; }
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 990  | Type: write | DISCREETS: Add item... = 1, Duplicate item... = 2, Separator 1 = -1, Edit item... = 10, Separator 2 = -2, Delete selected item(s) = 20</summary>
	public System.Object Collectivegoals_contextmenu_990 {get { return GetParameter(990); }set { SetParameter(990, value); }}
	/// <summary>PID: 990  | Type: write | DISCREETS: Add item... = 1, Duplicate item... = 2, Separator 1 = -1, Edit item... = 10, Separator 2 = -2, Delete selected item(s) = 20</summary>
	public System.Object Collectivegoals_contextmenu {get { return Write.Collectivegoals_contextmenu; }set { Write.Collectivegoals_contextmenu = value; }}
	/// <summary>PID: 991  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoals_autoinc_991 {get { return GetParameter(991); }set { SetParameter(991, value); }}
	/// <summary>PID: 991  | Type: read</summary>
	public System.Object Collectivegoals_autoinc {get { return GetParameter(991); }set { SetParameter(991, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsinstance_1001 {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1001  | Type: read</summary>
	public System.Object Collectivegoalsinstance {get { return GetParameter(1001); }set { SetParameter(1001, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsname_1002 {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1002  | Type: read</summary>
	public System.Object Collectivegoalsname {get { return GetParameter(1002); }set { SetParameter(1002, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsdescription_1003 {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1003  | Type: read</summary>
	public System.Object Collectivegoalsdescription {get { return GetParameter(1003); }set { SetParameter(1003, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Not Started = 0, In Progress = 1, Completed = 2, Paused = 3, Canceled = 4</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsstatus_1004 {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1004  | Type: read | DISCREETS: Not Started = 0, In Progress = 1, Completed = 2, Paused = 3, Canceled = 4</summary>
	public System.Object Collectivegoalsstatus {get { return GetParameter(1004); }set { SetParameter(1004, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsduedate_1005 {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	/// <summary>PID: 1005  | Type: read</summary>
	public System.Object Collectivegoalsduedate {get { return GetParameter(1005); }set { SetParameter(1005, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		collectivegoals = new CollectivegoalsQActionTable(this, 1000, "collectivegoals");
		Write = new WriteParameters(this);
	}
}
/// <summary>IDX: 0</summary>
public class CollectivegoalsQActionTable : QActionTable, IEnumerable<CollectivegoalsQActionRow>
{
	public CollectivegoalsQActionTable(SLProtocol protocol, int tableId, string tableName) : base(protocol, tableId, tableName) { }
	IEnumerator IEnumerable.GetEnumerator() { return (IEnumerator) GetEnumerator(); }
	public IEnumerator<CollectivegoalsQActionRow> GetEnumerator() { return new QActionTableEnumerator<CollectivegoalsQActionRow>(this); }
}
/// <summary>IDX: 0</summary>
public class CollectivegoalsQActionRow : QActionTableRow
{
	/// <summary>PID: 1001 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsinstance_1001 { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1001 | Type: read</summary>
	public System.Object Collectivegoalsinstance { get { if (base.Columns.ContainsKey(0)) { return base.Columns[0]; } else { return null; } } set { if (base.Columns.ContainsKey(0)) { base.Columns[0] = value; } else { base.Columns.Add(0, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsname_1002 { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1002 | Type: read</summary>
	public System.Object Collectivegoalsname { get { if (base.Columns.ContainsKey(1)) { return base.Columns[1]; } else { return null; } } set { if (base.Columns.ContainsKey(1)) { base.Columns[1] = value; } else { base.Columns.Add(1, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsdescription_1003 { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1003 | Type: read</summary>
	public System.Object Collectivegoalsdescription { get { if (base.Columns.ContainsKey(2)) { return base.Columns[2]; } else { return null; } } set { if (base.Columns.ContainsKey(2)) { base.Columns[2] = value; } else { base.Columns.Add(2, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsstatus_1004 { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1004 | Type: read</summary>
	public System.Object Collectivegoalsstatus { get { if (base.Columns.ContainsKey(3)) { return base.Columns[3]; } else { return null; } } set { if (base.Columns.ContainsKey(3)) { base.Columns[3] = value; } else { base.Columns.Add(3, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Collectivegoalsduedate_1005 { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	/// <summary>PID: 1005 | Type: read</summary>
	public System.Object Collectivegoalsduedate { get { if (base.Columns.ContainsKey(4)) { return base.Columns[4]; } else { return null; } } set { if (base.Columns.ContainsKey(4)) { base.Columns[4] = value; } else { base.Columns.Add(4, value); } } }
	public CollectivegoalsQActionRow() : base(0, 5) { }
	public CollectivegoalsQActionRow(System.Object[] oRow) : base(0, 5, oRow) { }
	public static implicit operator CollectivegoalsQActionRow(System.Object[] source) { return new CollectivegoalsQActionRow(source); }
	public static implicit operator System.Object[](CollectivegoalsQActionRow source) { return source.ToObjectArray(); }
}
}
